/**
 * The simple-icons (CC0) the site renders (Daily stack, project chips and every BrandIcon), as a typed slug → icon map. Import from here rather than
 * from `simple-icons` so only these icons are pulled in; the paths are inlined at build time by
 * `SimpleIcon.astro` and never reach the client.
 */
import {
  type SimpleIcon,
  siAstro,
  siBootstrap,
  siBun,
  siDocker,
  siDrizzle,
  siGit,
  siGithub,
  siGnubash,
  siJavascript,
  siJquery,
  siJsonwebtokens,
  siLaravel,
  siMarkdown,
  siMongodb,
  siMysql,
  siNestjs,
  siNextdotjs,
  siNodedotjs,
  siPhp,
  siPostgresql,
  siPrisma,
  siRabbitmq,
  siRailway,
  siReact,
  siRedis,
  siRemix,
  siSpotify,
  siTailwindcss,
  siThreedotjs,
  siTypescript,
  siUmami,
  siVercel,
  siVuedotjs,
} from 'simple-icons';

export const ICONS = {
  // Daily stack (task 15)
  typescript: siTypescript,
  nestjs: siNestjs,
  react: siReact,
  nodedotjs: siNodedotjs,
  nextdotjs: siNextdotjs,
  astro: siAstro,
  postgresql: siPostgresql,
  bun: siBun,
  tailwindcss: siTailwindcss,
  drizzle: siDrizzle,
  rabbitmq: siRabbitmq,
  docker: siDocker,
  vuedotjs: siVuedotjs,
  redis: siRedis,
  // Project chips (task 17)
  mysql: siMysql,
  threedotjs: siThreedotjs,
  jquery: siJquery,
  javascript: siJavascript,
  laravel: siLaravel,
  php: siPhp,
  bootstrap: siBootstrap,
  jsonwebtokens: siJsonwebtokens,
  umami: siUmami,
  // Brand icons (BrandIcon.astro: popular tags, footer, about)
  remix: siRemix,
  git: siGit,
  github: siGithub,
  gnubash: siGnubash,
  markdown: siMarkdown,
  prisma: siPrisma,
  vercel: siVercel,
  railway: siRailway,
  spotify: siSpotify,
  mongodb: siMongodb,
} as const satisfies Record<string, SimpleIcon>;

export type SimpleIconSlug = keyof typeof ICONS;

/** The 14 Daily stack slugs, in marquee order. */
export const STACK_SLUGS = [
  'typescript',
  'nestjs',
  'react',
  'nodedotjs',
  'nextdotjs',
  'astro',
  'postgresql',
  'bun',
  'tailwindcss',
  'drizzle',
  'rabbitmq',
  'docker',
  'vuedotjs',
  'redis',
] as const satisfies readonly SimpleIconSlug[];
