/**
 * ⌘K command palette (task 23): a plain React component mounted by `mount-palette.tsx`, never an
 * Astro island. Mockup `.cmdk` dialog.
 *
 * - Dialog: a native modal `<dialog>` (top layer, inert page behind it, Esc via `cancel`), so no
 *   extra Radix dependency. Focus returns to the element that opened it. Opened/closed through the
 *   `cmdk:open` / `cmdk:toggle` window events from CommandPaletteLoader.astro.
 * - List: `cmdk` with `shouldFilter={false}` (Pagefind ranks posts; pages/actions use `matchesQuery`).
 *   cmdk gives the input `role="combobox"` and the list `role="listbox"` with `aria-activedescendant`.
 * - Pagefind (`/pagefind/pagefind.js`, generated by `bun run build`) is imported on the first open.
 */
import { navigate } from 'astro:transitions/client';
import { Command } from 'cmdk';
import { type ReactNode, useCallback, useEffect, useLayoutEffect, useRef, useState } from 'react';
import { getTheme, resolveTheme, switchTheme, type ThemePref } from '~/lib/theme';
import {
  isExternal,
  isFile,
  MAX_RESULTS,
  matchesQuery,
  type PagefindFragment,
  type PaletteData,
  type PaletteLink,
  type PalettePost,
  toPalettePost,
} from './palette-data';

type PagefindResult = { id: string; data(): Promise<PagefindFragment> };
type Pagefind = {
  options(options: Record<string, unknown>): Promise<void>;
  init(): Promise<void> | void;
  debouncedSearch(term: string, options?: object, debounceMs?: number): Promise<{ results: PagefindResult[] } | null>;
};

type SearchState =
  | { status: 'idle' }
  | { status: 'loading'; query: string }
  | { status: 'done'; query: string; posts: PalettePost[] }
  | { status: 'unavailable' };

let pagefind: Promise<Pagefind> | undefined;

/** Loads and initialises Pagefind once per page life (the palette root is persisted across navigations). */
function loadPagefind(): Promise<Pagefind> {
  pagefind ??= (async () => {
    const path = '/pagefind/pagefind.js'; // a variable, so Vite leaves the runtime import alone
    const module = (await import(/* @vite-ignore */ path)) as Pagefind;
    await module.options({ excerptLength: 20 });
    await module.init();
    return module;
  })().catch((error: unknown) => {
    pagefind = undefined; // let the next open retry (e.g. a transient network error)
    throw error;
  });
  return pagefind;
}

/** Lucide paths (ISC), inlined so the chunk needs no icon package. */
const GLYPHS = {
  search: (
    <>
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </>
  ),
  post: (
    <>
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M16 13H8" />
      <path d="M16 17H8" />
    </>
  ),
  page: (
    <>
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </>
  ),
  contrast: (
    <>
      <circle cx="12" cy="12" r="10" />
      <path d="M12 18a6 6 0 0 0 0-12v12z" />
    </>
  ),
  light: (
    <>
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2M12 20v2m-7.07-17.07 1.41 1.41m11.32 11.32 1.41 1.41M2 12h2m16 0h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41" />
    </>
  ),
  dark: <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z" />,
  system: (
    <>
      <rect width="20" height="14" x="2" y="3" rx="2" />
      <path d="M8 21h8m-4-4v4" />
    </>
  ),
  link: (
    <>
      <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
      <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
    </>
  ),
  external: (
    <>
      <path d="M15 3h6v6M10 14 21 3" />
      <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
    </>
  ),
} satisfies Record<string, ReactNode>;

function Glyph({ name }: { name: keyof typeof GLYPHS }) {
  return (
    <svg
      className="cmdk-glyph"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      {GLYPHS[name]}
    </svg>
  );
}

type Action = { id: string; title: string; hint: string; glyph: keyof typeof GLYPHS; keywords: string[]; run(): void };

export default function CommandPalette({
  data,
  initialOpener,
}: {
  data: PaletteData;
  initialOpener: HTMLElement | null;
}) {
  const dialogRef = useRef<HTMLDialogElement>(null);
  const openerRef = useRef<HTMLElement | null>(initialOpener);
  const restoreFocusRef = useRef(true);
  const requestRef = useRef(0);
  const [open, setOpen] = useState(true);
  const [query, setQuery] = useState('');
  const [search, setSearch] = useState<SearchState>({ status: 'idle' });
  const [themePref, setThemePref] = useState<ThemePref>(getTheme);
  const [copied, setCopied] = useState(false);
  const [selected, setSelected] = useState('');

  const show = useCallback(() => {
    if (dialogRef.current?.open) return;
    openerRef.current = document.activeElement instanceof HTMLElement ? document.activeElement : null;
    setQuery('');
    setCopied(false);
    setThemePref(getTheme());
    setOpen(true);
  }, []);

  const close = useCallback((restoreFocus = true) => {
    restoreFocusRef.current = restoreFocus;
    setOpen(false);
  }, []);

  // Open state ↔ native dialog (layout effect: showModal before paint, so focus lands in the input).
  useLayoutEffect(() => {
    const dialog = dialogRef.current;
    if (!dialog) return;
    if (open && !dialog.open) {
      restoreFocusRef.current = true;
      dialog.showModal();
      // showModal() focuses the first focusable node (cmdk's root, tabindex -1): move it to the input.
      dialog.querySelector<HTMLInputElement>('[cmdk-input]')?.focus();
    } else if (!open && dialog.open) {
      dialog.close();
    }
  }, [open]);

  // Loader events, dialog events, and closing before a ClientRouter swap (a persisted modal must not move).
  useEffect(() => {
    const dialog = dialogRef.current;
    const onToggle = () => (dialogRef.current?.open ? close() : show());
    const onBeforeSwap = () => close(false);
    const onClose = () => {
      setOpen(false);
      const opener = openerRef.current;
      if (restoreFocusRef.current && opener?.isConnected) opener.focus({ preventScroll: true });
    };
    const onBackdrop = (event: MouseEvent) => {
      if (event.target === dialog) close();
    };
    window.addEventListener('cmdk:open', show);
    window.addEventListener('cmdk:toggle', onToggle);
    document.addEventListener('astro:before-swap', onBeforeSwap);
    dialog?.addEventListener('close', onClose);
    dialog?.addEventListener('click', onBackdrop);
    return () => {
      window.removeEventListener('cmdk:open', show);
      window.removeEventListener('cmdk:toggle', onToggle);
      document.removeEventListener('astro:before-swap', onBeforeSwap);
      dialog?.removeEventListener('close', onClose);
      dialog?.removeEventListener('click', onBackdrop);
    };
  }, [show, close]);

  // Pagefind on first open; then a debounced search per query (stale responses are dropped).
  useEffect(() => {
    if (open) loadPagefind().catch(() => setSearch({ status: 'unavailable' }));
  }, [open]);

  useEffect(() => {
    const term = query.trim();
    const request = ++requestRef.current;
    if (!term) {
      setSearch((current) => (current.status === 'unavailable' ? current : { status: 'idle' }));
      return;
    }
    setSearch((current) => (current.status === 'unavailable' ? current : { status: 'loading', query: term }));
    loadPagefind()
      .then(async (engine) => {
        const response = await engine.debouncedSearch(term, {}, 150);
        if (!response || request !== requestRef.current) return;
        const fragments = await Promise.all(response.results.slice(0, MAX_RESULTS).map((result) => result.data()));
        if (request !== requestRef.current) return;
        setSearch({ status: 'done', query: term, posts: fragments.map(toPalettePost) });
      })
      .catch(() => setSearch({ status: 'unavailable' }));
  }, [query]);

  const go = (href: string) => {
    if (isExternal(href)) {
      close();
      window.open(href, '_blank', 'noopener,noreferrer');
      return;
    }
    close(false);
    if (isFile(href)) location.assign(href);
    else void navigate(href);
  };

  const applyTheme = (pref: ThemePref) => {
    // Close synchronously first, so the reveal snapshots the page without the palette.
    restoreFocusRef.current = true;
    dialogRef.current?.close();
    setThemePref(pref);
    switchTheme(pref);
  };

  const copyUrl = () => {
    navigator.clipboard
      ?.writeText(location.href)
      .then(() => {
        setCopied(true);
        setTimeout(() => close(), 600);
      })
      .catch(() => close());
  };

  const term = query.trim();
  const themeHint = (pref: ThemePref) => (themePref === pref ? 'active' : '');
  const actions: Action[] = [
    {
      id: 'theme-toggle',
      title: 'Toggle light / dark theme',
      hint: resolveTheme(themePref) === 'dark' ? 'dark' : 'light',
      glyph: 'contrast',
      keywords: ['theme', 'mode', 'switch'],
      run: () => applyTheme(resolveTheme(getTheme()) === 'dark' ? 'light' : 'dark'),
    },
    {
      id: 'theme-light',
      title: 'Light theme',
      hint: themeHint('light'),
      glyph: 'light',
      keywords: ['theme', 'day'],
      run: () => applyTheme('light'),
    },
    {
      id: 'theme-dark',
      title: 'Dark theme',
      hint: themeHint('dark'),
      glyph: 'dark',
      keywords: ['theme', 'night'],
      run: () => applyTheme('dark'),
    },
    {
      id: 'theme-system',
      title: 'System theme',
      hint: themeHint('system'),
      glyph: 'system',
      keywords: ['theme', 'auto', 'os'],
      run: () => applyTheme('system'),
    },
    {
      id: 'copy-url',
      title: 'Copy page URL',
      hint: copied ? 'copied' : '',
      glyph: 'link',
      keywords: ['link', 'share', 'clipboard'],
      run: copyUrl,
    },
  ];

  const posts = term ? (search.status === 'done' && search.query === term ? search.posts : []) : data.posts;
  const pages = data.pages.filter((link) => matchesQuery(link, term));
  const shownActions = actions.filter((action) => matchesQuery({ ...action, href: '' }, term));
  const social = data.social.filter((link) => matchesQuery(link, term));
  const searching = term !== '' && (search.status === 'loading' || (search.status === 'done' && search.query !== term));
  const total = posts.length + pages.length + shownActions.length + social.length;

  // Explicit selection: the first visible item whenever the lists change (open, typing, async results),
  // so `aria-activedescendant` always points at an option and Enter never acts on a stale row.
  const visibleValues = [
    ...posts.map((post) => `post:${post.url}`),
    ...pages.map((link) => `page:${link.href}`),
    ...shownActions.map((action) => `action:${action.id}`),
    ...social.map((link) => `social:${link.href}`),
  ];
  const listKey = visibleValues.join('\n');
  const firstValue = visibleValues[0] ?? '';
  // biome-ignore lint/correctness/useExhaustiveDependencies: `listKey` (the visible list) and `open` are the triggers.
  useEffect(() => {
    setSelected(firstValue);
  }, [listKey, open]);

  // cmdk only derives `aria-activedescendant` on its internal selection path, not from a controlled
  // `value`; every selection change goes through `selected`, so mirror it onto the combobox here.
  // biome-ignore lint/correctness/useExhaustiveDependencies: re-run when the rendered list changes too.
  useLayoutEffect(() => {
    const dialog = dialogRef.current;
    const input = dialog?.querySelector('[cmdk-input]');
    if (!dialog || !input) return;
    const item = selected ? dialog.querySelector(`[cmdk-item][data-value="${CSS.escape(selected)}"]`) : null;
    if (item?.id) input.setAttribute('aria-activedescendant', item.id);
    else input.removeAttribute('aria-activedescendant');
    item?.scrollIntoView({ block: 'nearest' });
  }, [selected, listKey, open]);

  const status =
    search.status === 'unavailable' && term
      ? 'Full-text search is unavailable: the index is built by bun run build.'
      : searching
        ? 'Searching…'
        : term
          ? `${total} result${total === 1 ? '' : 's'}`
          : '';

  const linkItem = (link: PaletteLink, group: string, glyph: keyof typeof GLYPHS) => (
    <Command.Item
      key={link.href}
      value={`${group}:${link.href}`}
      data-value={`${group}:${link.href}`}
      className="cmdk-item"
      onSelect={() => go(link.href)}
    >
      <Glyph name={glyph} />
      <span className="cmdk-main">
        <span className="cmdk-title">{link.title}</span>
      </span>
      <span className="cmdk-sub">{link.hint}</span>
    </Command.Item>
  );

  return (
    <dialog ref={dialogRef} className="cmdk-back" aria-label="Command menu">
      <div className="cmdk">
        <Command
          label="Command menu"
          shouldFilter={false}
          loop
          vimBindings={false}
          value={selected}
          onValueChange={setSelected}
        >
          <div className="cmdk-in">
            <Glyph name="search" />
            <Command.Input
              value={query}
              onValueChange={setQuery}
              placeholder="Search posts, pages, actions…"
              aria-label="Search posts, pages and actions"
            />
            <button type="button" className="cmdk-esc" onClick={() => close()} aria-label="Close command menu">
              <kbd>esc</kbd>
            </button>
          </div>
          <Command.List className="cmdk-list" label="Results">
            {search.status === 'unavailable' && term && (
              <p className="cmdk-note">
                Full-text search needs the Pagefind index: run <code>bun run build</code>, then serve the build.
              </p>
            )}
            {searching && posts.length === 0 && (
              <Command.Loading className="cmdk-note">Searching posts…</Command.Loading>
            )}
            {posts.length > 0 && (
              <Command.Group heading={term ? 'Posts' : 'Latest posts'}>
                {posts.map((post) => (
                  <Command.Item
                    key={post.url}
                    value={`post:${post.url}`}
                    data-value={`post:${post.url}`}
                    className="cmdk-item"
                    onSelect={() => go(post.url)}
                  >
                    <Glyph name="post" />
                    <span className="cmdk-main">
                      <span className="cmdk-title">{post.title}</span>
                      {post.excerpt ? (
                        <span
                          className="cmdk-excerpt"
                          // biome-ignore lint/security/noDangerouslySetInnerHtml: Pagefind HTML-escapes excerpts and only adds <mark>.
                          dangerouslySetInnerHTML={{ __html: post.excerpt }}
                        />
                      ) : null}
                    </span>
                    {post.tags.length > 0 && <span className="cmdk-sub">{post.tags.slice(0, 2).join(' · ')}</span>}
                  </Command.Item>
                ))}
              </Command.Group>
            )}
            {pages.length > 0 && (
              <Command.Group heading="Navigation">{pages.map((link) => linkItem(link, 'page', 'page'))}</Command.Group>
            )}
            {shownActions.length > 0 && (
              <Command.Group heading="Actions">
                {shownActions.map((action) => (
                  <Command.Item
                    key={action.id}
                    value={`action:${action.id}`}
                    data-value={`action:${action.id}`}
                    className="cmdk-item"
                    onSelect={action.run}
                  >
                    <Glyph name={action.glyph} />
                    <span className="cmdk-main">
                      <span className="cmdk-title">{action.title}</span>
                    </span>
                    {action.hint && <span className="cmdk-sub">{action.hint}</span>}
                  </Command.Item>
                ))}
              </Command.Group>
            )}
            {social.length > 0 && (
              <Command.Group heading="Social">
                {social.map((link) => linkItem(link, 'social', 'external'))}
              </Command.Group>
            )}
            {term && !searching && total === 0 && <p className="cmdk-empty">No results for “{term}”</p>}
          </Command.List>
          <div className="cmdk-foot">
            <span>
              <kbd>↑</kbd> <kbd>↓</kbd> move
            </span>
            <span>
              <kbd>↵</kbd> open
            </span>
            <span className="cmdk-foot-end">Full-text search by Pagefind</span>
          </div>
          <p className="sr-only" aria-live="polite">
            {status}
          </p>
        </Command>
      </div>
    </dialog>
  );
}
